const COORDINADOR = 'COORDINADOR';
const DOCENTE = 'PROFESOR';
const ESTUDIANTE = 'ESTUDIANTE';

export const roles = {
  COORDINADOR: COORDINADOR,
  DOCENTE: DOCENTE,
  ESTUDIANTE: ESTUDIANTE,
};

export const actual = COORDINADOR;
